<div id="profileOverlayContainer">
    <div class="profileLine">
        <strong>Username <a href="<?= $this->basePath('profile') ?>" target="_profile">(View Profile)</a></strong><div class="info">TODO - FROM IDENTITY</div>
    </div>
    <div class="profileLine">
        <strong>Email</strong><div class="info">TODO - FROM IDENTITY</div>
    </div>
    <div class="profileLine">
        <strong>Access Role</strong><div class="info"><?= ucfirst($this->identity()->getRoleName()) ?></div>
    </div>
</div>